[shell]
program = "/opt/homebrew/bin/fish"

[window]
decorations = "None"
opacity = 0.75
startup_mode = "Maximized"

[font]
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }
size = 16
